language: python
python: 3.6

services:
  - docker

before_install:
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

install:
  - docker-compose up -d

script:
  - docker-compose exec api python manage.py test