# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TooPathAPI', '0002_location_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
