# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 09:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actual_locations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('did', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('height', models.FloatField(default=None, null=True)),
                ('speed', models.FloatField(default=None, null=True)),
                ('heading', models.FloatField(default=None, null=True)),
                ('utc', models.DateTimeField(db_index=True, default=None, null=True)),
                ('device_privacy', models.CharField(choices=[('pr', 'Private'), ('pu', 'Public'), ('an', 'Anonymous'), ('fr', 'Friends')], default='pr', max_length=2)),
                ('device_type', models.CharField(choices=[('ad', 'Android'), ('io', 'iPhone'), ('wp', 'Windows Phone'), ('en', 'Enfora')], default='ad', max_length=2)),
                ('device_imei', models.CharField(max_length=40, null=True)),
                ('actual_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TooPath3.ActualLocation')),
                ('owner', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='RouteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'route_locations',
                'abstract': False,
            },
        ),
    ]
