# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TooPath3', '0004_auto_20171107_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='port_number',
            field=models.IntegerField(null=True),
        ),
    ]
