# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TooPath3', '0005_auto_20171108_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='TooPath3.Device'),
        ),
    ]
