# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TooPath3', '0006_auto_20171108_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklocation',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='TooPath3.Track'),
        ),
    ]
