# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('did', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('height', models.FloatField(default=None, null=True)),
                ('speed', models.FloatField(default=None, null=True)),
                ('heading', models.FloatField(default=None, null=True)),
                ('utc', models.DateTimeField(db_index=True, default=None, null=True)),
                ('device_type', models.CharField(choices=[('ad', 'Android'), ('io', 'iPhone'), ('wp', 'Windows Phone'), ('en', 'Enfora')], default='ad', max_length=2)),
                ('device_imei', models.CharField(max_length=40, null=True)),
                ('device_privacy', models.CharField(choices=[('pr', 'Private'), ('pu', 'Public'), ('an', 'Anonymous'), ('fr', 'Friends')], default='pr', max_length=2)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_did', to='api.Device')),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
